### ISSUE TITLE
README.md file Missing

### ISSUE THREAD

**Issue by bottydim** [MadryLab/robustness_lib#1]
setup.py requires a README file:

```
# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
```

**Comment by sonamsingh19** [comment]
I put long_description ='' and it worked.

**Comment by andrewilyas** [comment]
Hi all, 

This was just an early version of https://github.com/MadryLab/robustness, which is a fully packaged and installable version, with detailed documentation at robustness.readthedocs.io. That is probably what you want to actually use :)
